### ISSUE TITLE
Changes to algorithm has broken support?

### ISSUE THREAD

**Issue by n0kt** [ffluegel/zippyshare#5]
```
./zippyshare.sh: line 64: 168851%1000
01%20
201%201080
0%20+11 : syntax error in expression (error token is "01%20
201%201080
0%20+11 ")
My%20File.7z.001
######################################################################## 100.0%
```

Appears to be currently broken this is the output I'm getting back when trying to download. Happens with single links as well as from a list.

**Comment by ffluegel** [comment]
Sorry, should be fixed now

**Comment by n0kt** [comment]
> Sorry, should be fixed now

Doesn't appear to be working and according to [a comment here](https://github.com/img2tab/zippyshare/issues/9#issuecomment-453934655) Zippyshare has made a change to the algorithm that now requires a javascript parser.

**Comment by img2tab** [comment]
It doesn't explicitly require a javascript parser, and javascript algorithm can probably be implemented in a shell script. The thing is that any _change_ in the algoritm would break the script, and the correct robust-to-change solution is to use a javascript parser to parse the javascript instead of manually implementing it every time it updates.
